feat: patch supautils sha
supabase/postgres pull request #1026
Opened 2024-07-04 06:00 UTC by J0

Currently it seems like the [SHA256sum is inaccurate](https://github.com/supabase/postgres/actions/runs/9789146863/job/27028480566#step:6:1191) which is leading to a build error

2024-07-04 06:13 UTC, soedirgo approved these changes

2024-07-04 09:11 UTC, darora commented
What's changed? The version was changed [a month ago](https://github.com/supabase/postgres/pull/989/files), and we've had releases since then.

2024-07-04 10:27 UTC, J0 commented
Not much has changed - I realized after opening the PR that this doesn't block the release. Figured we might as well patch though. Also fine to close.

2024-07-05 00:10 UTC, darora commented
That's actually bad as well, since a sha mismatch _should_ break the build and cause a release failure?

2024-07-06 02:29 UTC, samrose requested changes
@darora @J0 

To address the checksum issue that Div raised in this PR

I think you are going to need something like this

```
diff --git a/Dockerfile b/Dockerfile
index 88f5575..b703703 100644
--- a/Dockerfile
+++ b/Dockerfile
@@ -824,7 +824,9 @@ RUN checkinstall -D --install=no --fstrans=no --backup=no --pakdir=/tmp --nodoc
 FROM base as supautils
 # Download package archive
 ARG supautils_release
-ADD "https://github.com/supabase/supautils/releases/download/v${supautils_release}/supautils-v${supautils_release}-pg${postgresql_major}-${TARGETARCH}-linux-gnu.deb" \
+ARG supautils_release_checksum
+ADD --checksum=${supautils_release_checksum} \
+    "https://github.com/supabase/supautils/releases/download/v${supautils_release}/supautils-v${supautils_release}-pg${postgresql_major}-${TARGETARCH}-linux-gnu.deb" \
     /tmp/supautils.deb
 
 ####################
```

2024-07-06 12:53 UTC, J0 commented
> That's actually bad as well, since a sha mismatch should break the build and cause a release failure?

Yes, a sha mismatch should break the build and cause a release failure. I wasn't too sure if the resulting sha mismatch was intentional or something that had gone unnoticed for a long while.

Let's close this PR as it sounds like the proper fix here would be to patch the Dockerfile rather than the Shasum

2024-07-06 12:53 UTC, closed without merging