chore: bump gotrue version to v2.157.1
supabase/postgres pull request #1077
Opened 2024-07-31 17:19 UTC by kangmingtay

## What kind of change does this PR introduce?
* See [changelog](https://github.com/supabase/auth/compare/v2.156.0...v2.157.1) - this version of gotrue introduces the changes made to support asymmetric JWTs to projects 

## What is the current behavior?

Please link any relevant issues here.

## What is the new behavior?

Feel free to include screenshots if it includes visual changes.

## Additional context

Add any other context or screenshots.

2024-07-31 18:36 UTC, kangmingtay commented
CI failing doesn't seem to be a blocker as previously mentioned in: https://supabase.slack.com/archives/C01D6TWFFFW/p1721956878767859?thread_ts=1721954162.433929&cid=C01D6TWFFFW

2024-07-31 20:04 UTC, samrose commented
> CI failing doesn't seem to be a blocker as previously mentioned in: https://supabase.slack.com/archives/C01D6TWFFFW/p1721956878767859?thread_ts=1721954162.433929&cid=C01D6TWFFFW

@kangmingtay I have a PR up to fix that feature to fwiw https://github.com/supabase/postgres/pull/1080

2024-07-31 20:06 UTC, samrose requested changes, later dismissed
I believe it is the case that we will need to start bumping the patch version of https://github.com/supabase/postgres/blob/develop/common-nix.vars.pkr.hcl as well, as it is using the same deps going to ping @darora to see if he agrees on that?

2024-07-31 23:04 UTC, kangmingtay commented
@samrose ok i just bumped it in case - seems like it doesn't do any harm

2024-08-01 00:14 UTC, darora approved these changes

2024-08-01 00:14 UTC, darora commented
Yes, both the versions need to be bumped at the moment.

2024-08-01 00:15 UTC, merged