bump to postgrest v12.2.3
supabase/postgres pull request #1081
Opened 2024-08-01 20:27 UTC by steve-chavez

New patch release https://github.com/PostgREST/postgrest/releases/tag/v12.2.3

Includes an important fix for a regression https://github.com/PostgREST/postgrest/pull/3670.

2024-08-01 21:11 UTC, samrose commented
@steve-chavez please disregard nix ci failure I’ll need to account for when or is on fork as well as branch.

2024-08-01 22:31 UTC, samrose requested changes
@steve-chavez I think we also need to bump https://github.com/supabase/postgres/blob/develop/common-nix.vars.pkr.hcl file to *.102 as well now that we have distributed that AMI

2024-08-01 23:15 UTC, steve-chavez commented
>  I think we also need to bump https://github.com/supabase/postgres/blob/develop/common-nix.vars.pkr.hcl file to *.102 as well now that we have distributed that AMI

@samrose Done :white_check_mark:

2024-08-02 01:05 UTC, samrose approved these changes

2024-08-02 02:05 UTC, darora approved these changes

2024-08-02 02:05 UTC, merged