bump to pg_net 0.13.0
supabase/postgres pull request #1311
Opened 2024-11-05 19:08 UTC by steve-chavez

This is now compatible with macos, so it also reverts "feat: tmp disable pg_net on macos and allow for server start on macos (#1289) 7db7e1a9e34b9ffb9b0e3372ccf08eb4fa772f4b.

- CHANGELOG for v0.12.0: https://github.com/supabase/pg_net/releases/tag/v0.12.0
- CHANGELOG for v0.13.0: https://github.com/supabase/pg_net/releases/tag/v0.13.0

Please go the the `Preview` tab and select the appropriate sub-template:

* [Default](?expand=1&template=default.md)
* [Extension Upgrade](?expand=1&template=extension_upgrade.md)

2024-11-05 20:24 UTC, delgado3d approved these changes

2024-11-05 20:24 UTC, delgado3d commented
bump ami version?

2024-11-05 20:41 UTC, samrose requested changes
@steve-chavez can you also please bump the versions in ansible/vars.yml to create new overall release? Thank you

2024-11-06 11:58 UTC, samrose approved these changes

2024-11-06 14:21 UTC, merged