feat: enable GTiff GDAL driver for PostGIS raster
supabase/postgres pull request #1351
Opened 2024-12-02 17:34 UTC by lookevink

## Description
Enable GTiff GDAL driver by default for PostGIS raster functionality.

## Problem
Currently, despite postgis_raster being enabled, none of the required GDAL drivers are enabled, leading to:
`rt_util_gdal_open: Cannot open file. All GDAL drivers disabled`

## Solution
- Add `postgis.gdal_enabled_drivers = 'GTiff'` to platform defaults configuration
- Ensure postgresql-platform-defaults.conf is properly included in main PostgreSQL configuration
- Set appropriate file permissions and ownership

## Changes
1. Added to `postgresql-platform-defaults.conf`:

2025-08-27 14:40 UTC, hunleyd commented
@lookevink is this PR still valid and in need of review?

2025-08-27 14:53 UTC, lookevink commented
@hunleyd will need to resolve conflicts. do you know what the process for reviewing & merging PRs is?

2025-08-27 15:37 UTC, hunleyd commented
> @hunleyd will need to resolve conflicts. do you know what the process for reviewing & merging PRs is?

reviewing? yes
merging? not so much

2025-09-08 15:26 UTC, hunleyd requested changes

2025-09-08 15:26 UTC, hunleyd commented on Dockerfile-156
> +    chmod 644 /etc/postgresql-custom/postgresql-platform-defaults.conf
```suggestion
    install -m 0644 -g postgres -o postgres /dev/null /etc/postgresql-custom/postgresql-platform-defaults.conf
```

2025-09-09 14:38 UTC, hunleyd approved these changes

2025-09-09 14:45 UTC, samrose commented
Hi just wanted to update that this approach won't achieve updating this driver in our hosted platform. We had left a comment that we're looking into the feasibility on our platform with enabling this https://github.com/supabase/postgres/issues/1347#issuecomment-3025325179 

There are security concerns with enabling it on our platform, and until we have a pathway to resolving that, we cannot enable it. If we decide to enable this we'll be sure update the issue above and our changelog. We're sorry for any issue that may cause our users, and we understand the frustration our users may feel when we cannot support configuration, or aspects of extensions etc. We'll do our best to try and support this when we can. For now I will have to close this PR until we can address internally the security issues with enabling this.

2025-09-09 14:45 UTC, closed without merging

2025-09-09 14:46 UTC, samrose commented
If you are just trying to use this locally, self-hosted, or in your own docker container, it should be no problem to adjust the configuration as done in this PR.