Add index_advisor extension to image
supabase/postgres pull request #933
Opened 2024-04-03 21:24 UTC by olirice

Adds the `index_advisor` extension for LW11 index advisor report feature.

2024-04-05 19:18 UTC, samrose requested changes
Everything looks good but I wasn't 100% sure if this error is the result of a syntax problem in the dockerfile? https://github.com/supabase/postgres/actions/runs/8574463100/job/23501349016?pr=933#step:8:230

2024-04-05 19:46 UTC, olirice commented
It's been happening in other branches too. I think its unrelated but `supabase/backend` will know when they review

2024-04-05 20:00 UTC, samrose approved these changes

2024-04-08 06:58 UTC, darora approved these changes
Approving, the test failure you're seeing right now is almost certainly tied to some infra changes to our testing environment.

2024-04-08 19:51 UTC, merged