feat: revoke supabase_storage_admin from postgres
supabase/postgres pull request #994
Opened 2024-06-06 06:06 UTC by soedirgo

2025-04-30 14:37 UTC, steve-chavez commented on migrations/db/migrations/20250421084701_revoke_supabase_storage_admin_from_postgres.sql
> +revoke all on auth.schema_migrations from dashboard_user, postgres;
The `revoke all` privileges on the migrations tables are not covered by tests. We should add those to ensure no regressions.

2025-04-30 14:49 UTC, steve-chavez requested changes
We need some covering tests as mentioned above.

2025-04-30 22:36 UTC, steve-chavez commented
Merged https://github.com/supabase/postgres/pull/1577 to help with the testing. Now this PR would just need a rebase.

2025-05-01 08:12 UTC, soedirgo commented
Rebased the PR

2025-05-01 19:49 UTC, steve-chavez commented
Tests need to be adjusted, see [logs](https://productionresultssa9.blob.core.windows.net/actions-results/a9b95899-57c0-4499-a3dd-c1987d9849f3/workflow-job-run-58980661-3526-5e14-f5d1-cc92cb5e6954/logs/job/job-logs.txt?rsct=text%2Fplain&se=2025-05-01T19%3A55%3A21Z&sig=WvYF23g1y6ILneI6u2OWcUgi7no%2BeHQnyU1BIFmGt7c%3D&ske=2025-05-02T05%3A31%3A37Z&skoid=ca7593d4-ee42-46cd-af88-8b886a2f84eb&sks=b&skt=2025-05-01T17%3A31%3A37Z&sktid=398a6654-997b-47e9-b12b-9515b896b4de&skv=2025-05-05&sp=r&spr=https&sr=b&st=2025-05-01T19%3A45%3A16Z&sv=2025-05-05) (do ctrl+f "regression.diffs").

Looks like these lines have to be removed:

https://github.com/supabase/postgres/blob/24f17a3c83d6b2962d2776d87f62a77b9757cf08/nix/tests/expected/auth.out#L135-L148

2025-05-02 07:16 UTC, soedirgo commented
Thanks, all fixed now

2025-05-02 11:04 UTC, steve-chavez approved these changes

2025-05-02 11:11 UTC, steve-chavez commented on nix/tests/expected/storage.out
> - storage     | migrations | anon                   | INSERT         | f
Quite surprising to see the API roles having privileges over storage internal tables.

2025-05-02 16:28 UTC, merged